# Generated by Django 3.0 on 2022-02-21 12:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 12, 14, 47, 348556, tzinfo=utc)),
        ),
    ]
