# Generated by Django 3.0 on 2022-03-20 11:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_auto_20220221_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 20, 11, 30, 35, 96332, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=255, unique_for_date='publish'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lesson.Material')),
            ],
        ),
    ]
