# Generated by Django 3.0 on 2022-03-22 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0005_auto_20220322_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=255, unique_for_date='publish')),
                ('body', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updeted', models.DateField(auto_now=True)),
                ('publish', models.DateTimeField(default=datetime.datetime(2022, 3, 22, 12, 30, 0, 526375, tzinfo=utc))),
                ('team_type', models.CharField(choices=[('группа A', 'Группа А в НБЛ'), ('группа B', 'Группа В в НБЛ')], default='руппа А', max_length=25)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='material',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lesson.Team'),
            preserve_default=False,
        ),
    ]
