# Generated by Django 3.0 on 2022-03-22 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_auto_20220322_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 22, 14, 52, 59, 100423, tzinfo=utc)),
        ),
    ]
