# Generated by Django 3.0 on 2022-03-23 13:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_auto_20220322_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 23, 13, 23, 29, 457291, tzinfo=utc)),
        ),
    ]
