# Generated by Django 3.0 on 2022-03-24 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_auto_20220323_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 10, 31, 5, 583293, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('Группа A', 'Группа А в НБЛ'), ('Группа B', 'Группа В в НБЛ')], default='руппа А', max_length=25),
        ),
    ]
