# Generated by Django 3.0 on 2022-03-24 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_admin_geomap


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_auto_20220324_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
        migrations.AlterField(
            model_name='team',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 12, 18, 3, 338364, tzinfo=utc)),
        ),
    ]
