# Generated by Django 3.0 on 2022-03-24 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_auto_20220324_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterField(
            model_name='team',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 24, 13, 31, 41, 662142, tzinfo=utc)),
        ),
    ]
